/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParikramaRouteImport } from './routes/parikrama'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptRefRouteImport } from './routes/receipt.$ref'

const ParikramaRoute = ParikramaRouteImport.update({
  id: '/parikrama',
  path: '/parikrama',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptRefRoute = ReceiptRefRouteImport.update({
  id: '/receipt/$ref',
  path: '/receipt/$ref',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/parikrama': typeof ParikramaRoute
  '/receipt/$ref': typeof ReceiptRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/parikrama': typeof ParikramaRoute
  '/receipt/$ref': typeof ReceiptRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/parikrama': typeof ParikramaRoute
  '/receipt/$ref': typeof ReceiptRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/donate'
    | '/gallery'
    | '/history'
    | '/parikrama'
    | '/receipt/$ref'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/donate'
    | '/gallery'
    | '/history'
    | '/parikrama'
    | '/receipt/$ref'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/donate'
    | '/gallery'
    | '/history'
    | '/parikrama'
    | '/receipt/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DonateRoute: typeof DonateRoute
  GalleryRoute: typeof GalleryRoute
  HistoryRoute: typeof HistoryRoute
  ParikramaRoute: typeof ParikramaRoute
  ReceiptRefRoute: typeof ReceiptRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parikrama': {
      id: '/parikrama'
      path: '/parikrama'
      fullPath: '/parikrama'
      preLoaderRoute: typeof ParikramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$ref': {
      id: '/receipt/$ref'
      path: '/receipt/$ref'
      fullPath: '/receipt/$ref'
      preLoaderRoute: typeof ReceiptRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DonateRoute: DonateRoute,
  GalleryRoute: GalleryRoute,
  HistoryRoute: HistoryRoute,
  ParikramaRoute: ParikramaRoute,
  ReceiptRefRoute: ReceiptRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
